- hosts: all
  user: root
  sudo: true
  tasks:
     - name: Downloading ropo file
       yum_repository:
         name: cassandra
         description: cassandra 
         baseurl: https://www.apache.org/dist/cassandra/redhat/311x/
         gpgcheck: no
         enabled: yes
     - name: install the latest version of cassandra
       yum:
          name: cassandra
          state: latest
         
